FROM debian:buster-20210621-slim

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

ENV USER=circleci

# packages required for use as a circleci remote-docker primary container
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git=1:2.20.1-2+deb10u3 \
            openssh-server=1:7.9p1-10+deb10u2 \
            tar=1.30+dfsg-6 \
            gzip=1.9-3 \
            ca-certificates=20200601~deb10u2 \
            sudo=1.8.27-1+deb10u3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -g 3434 $USER && useradd -u 3434 -g $USER -G sudo -m -s /bin/bash $USER && \
    sed -i /etc/sudoers -re 's/^%sudo.*/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' && \
    sed -i /etc/sudoers -re 's/^root.*/root ALL=(ALL:ALL) NOPASSWD: ALL/g' && \
    sed -i /etc/sudoers -re 's/^#includedir.*/## **Removed the include directive** ##"/g' && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p /home/circleci/project && \
    chown -R $USER:$USER /home/circleci/project

# echo "Customized the sudoers file for passwordless access to the foo user!" && \
# echo "foo user:";  su - foo -c id
# RUN apk add --no-cache \
#         git==2.32.0-r0 \
#         openssh==8.6_p1-r2 \
#         tar==1.34-r0 \
#         gzip==1.10-r1 \
#         ca-certificates==20191127-r5 \
#         sudo==1.9.7_p1-r1 && \
#     addgroup --gid 3434 -S $USER && \
#     adduser --uid 3434 --ingroup $USER --disabled-password $USER && \
#     echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER && \
#     chmod 0440 /etc/sudoers.d/$USER && \
#     mkdir -p /home/circleci/project && \
#     chown -R $USER:$USER /home/circleci/project

USER circleci

WORKDIR /home/circleci/project

HEALTHCHECK NONE
