FROM debian:buster-slim

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# minimum packages required for use as a circleci remote-docker primary container
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git \
            openssh-server \
            tar \
            gzip \
            ca-certificates
