FROM debian:buster-20210621-slim

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# minimum packages required for use as a circleci remote-docker primary container
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git=1:2.20.1-2+deb10u3 \
            openssh-server=1:7.9p1-10+deb10u2 \
            tar=1.30+dfsg-6 \
            gzip=1.9-3 \
            ca-certificates=20200601~deb10u2
