---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  snyk: snyk/snyk@0.0.10

# yaml anchor filters
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/


workflows:
  di-circleci-remote-docker-image-pipeline:
    jobs:
      - docker/hadolint:
          filters: *on-push-master
      - docker/publish:
          name: test-build
          context: ZTW
          deploy: true
          image: twdps/di-circleci-remote-docker
          lint-dockerfile: true
          tag: edge
          requires:
            - docker/hadolint
          filters: *on-push-master
          after_build:
            - snyk/scan:
                docker-image-name: twdps/di-circleci-remote-docker:edge
                organization: twdps
                fail-on-issues: true
                monitor-on-build: false
            - run:
                command: |
                  CID=$(docker run --name cis-test-di-circleci-remote-docker \
                                   -it -d --entrypoint "/bin/ash" \
                                   "twdps/di-circleci-remote-docker:edge")
                  docker run -it \
                             -v /var/run/docker.sock:/var/run/docker.sock \
                             -e IMAGE_NAME="twdps/di-circleci-remote-docker" \
                             -e IMAGE_TAG="edge" \
                             -e CID="$CID" \
                             "feedyard/docker-benchmark" distroless
                  docker run -it --rm \
                            -v /var/run/docker.sock:/var/run/docker.sock \
                            -e CHEF_LICENSE="accept" \
                            -v "$(pwd)":/share \
                            chef/inspec exec profiles/circleci-remote-docker \
                            -t docker://"${CID}"
      - docker/publish:
          name: release
          context: ZTW
          image: twdps/di-circleci-remote-docker
          tag: '$CIRCLE_TAG,stable'
          filters: *on-tag-master


  # currently circleci does not support scheduled builds that use restricted contexts
  #
  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  # di-circleci-remote-docker-image-nightly-build:
  #   triggers:
  #     - schedule:
  #         cron: "0 6 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - docker/publish:
  #         name: nightly-build
  #         context: ZTW
  #         deploy: false
  #         image: twdps/di-circleci-remote-docker
  #         lint-dockerfile: true
  #         tag: nightly
  #         after_build:
  #           - snyk/scan:
  #               docker-image-name: twdps/di-circleci-remote-docker:edge
  #               organization: twdps
  #               fail-on-issues: true
  #               monitor-on-build: false
