---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@dev:5cc97ad

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  di-circleci-remote-docker-image-alpine-pipeline:
    jobs:
      - executor-tools/dev-release:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: alpine-dev-build
          context: twdps-di
          dockerfile: Dockerfile.alpine
          image: twdps/di-circleci-remote-docker
          tag: alpine-edge
          cis-docker-image-scan: true
          bats-test: true
          entry-point: /bin/ash
          container-name: di-circleci-remote-docker-edge
          filters: *on-push-master

      - executor-tools/publish:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: alpine-release
          context: twdps-di
          pull-tag: alpine-edge
          image: twdps/di-circleci-remote-docker
          release-tag: alpine-stable
          filters: *on-tag-master

  di-circleci-remote-docker-image-slim-pipeline:
    jobs:
      - executor-tools/dev-release:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: slim-dev-build
          context: twdps-di
          dockerfile: Dockerfile.slim
          image: twdps/di-circleci-remote-docker
          tag: slim-edge
          cis-docker-image-scan: true
          bats-test: true
          entry-point: /bin/bash
          container-name: di-circleci-remote-docker-edge
          filters: *on-push-master

      - executor-tools/publish:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: Release
          context: twdps-di
          pull-tag: edge
          image: twdps/di-circleci-remote-docker
          release-tag: stable
          filters: *on-tag-master

  # NOTE: currently circleci does not support scheduled builds that use restricted contexts
  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  # di-circleci-infra-image-nightly-build:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * 0"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - executor-tools/dev-release:
  #         shell: secrethub run -- /bin/sh -eo pipefail
  #         name: "nightly-build"
  #         context: twdps-di
  #         image: twdps/di-circleci-remote-docker
  #         tag: nightly
  #         dockerfile: Dockerfile.alpine.unpinned
  #         docker-cve-scan: false
  #         cis-docker-image-scan: true
  #         bats-test: true
  #         entry-point: /bin/ash
  #         container-name: di-circleci-remote-docker-edge
