---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@2.1.0

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  di-circleci-remote-docker-image-pipeline:
    jobs:
      - executor-tools/dev-release:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: "dev-build"
          context: twdps-di
          image: twdps/di-circleci-remote-docker
          tag: edge
          docker-cve-scan: true
          snyk-organization: twdps
          cis-docker-image-scan: true
          bats-test: true
          entry-point: /bin/ash
          container-name: di-circleci-remote-docker-edge
          filters: *on-push-master
          
      - executor-tools/publish:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: Release
          context: twdps-di
          pull-tag: edge
          image: twdps/di-circleci-remote-docker
          release-tag: stable
          filters: *on-tag-master        

  # NOTE: currently circleci does not support scheduled builds that use restricted contexts
  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  di-circleci-infra-image-nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - executor-tools/dev-release:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: "nightly-build"
          context: twdps-di
          image: twdps/di-circleci-remote-docker
          tag: nightly
          dockerfile: Dockerfile.unpinned
          docker-cve-scan: true
          snyk-organization: twdps
          cis-docker-image-scan: true
          bats-test: true
          entry-point: /bin/ash
          container-name: di-circleci-remote-docker-edge
