---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  snyk: snyk/snyk@0.0.10

# yaml anchor filters
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/


workflows:
  di-circleci-remote-docker-image-pipeline:
    jobs:
      - docker/hadolint:
          filters: *on-push-master
      - docker/publish:
          name: test-build
          context: ZTW
          deploy: false
          image: thoughtworks-dps/di-circleci-remote-docker
          lint-dockerfile: true
          tag: edge
          requires:
            - docker/hadolint
          filters: *on-push-master
          after_build:
            - snyk/scan:
                docker-image-name: thoughtworks-dps/di-circleci-remote-docker:edge
                organization: thoughtworks-dps
                fail-on-issues: false
                monitor-on-build: false
            - run:
                command: |
                  CID=$(docker run --name cis-test-di-circleci-remote-docker \
                                   -it -d --entrypoint "/bin/ash" \
                                   "thoughtworks-dps/di-circleci-remote-docker:edge")
                  docker run -it \
                             -v /var/run/docker.sock:/var/run/docker.sock \
                             -e IMAGE_NAME="thoughtworks-dps/di-circleci-remote-docker" \
                             -e IMAGE_TAG="edge" \
                             -e CID="$CID" \
                             "feedyard/docker-benchmark" standard
      - docker/publish:
          name: release
          context: ci
          image: thoughtworks-dps/di-circleci-remote-docker
          tag: '$CIRCLE_TAG,stable'
          filters: *on-tag-master



  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  # circleci-remote-docker-executor-nightly-build:
  #   triggers:
  #     - schedule:
  #         cron: "0 6 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - executor-tools/dev-release:
  #         name: nightly-build
  #         context: executor-publishing
  #         image: feedyard/circleci-remote-docker
  #         dockerfile: Dockerfile.unpinned
  #         tag: nightly
  #         after-build:
  #           - run:
  #               name: configuration testing
  #               command: ash test_nightly.sh
